Studio.create(id: 1, title: "Castle Rock")
Studio.create(id: 2, title: "MiramaxFilms")
Studio.create(id: 3, title: "RegencyEnterprises")
Studio.create(id: 4, title: "Pixar")
Studio.create(id: 5, title: "Disney")
